# Generated by Django 3.0.5 on 2020-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_pengguna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pengguna', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=15)),
                ('tipe', models.CharField(max_length=15)),
            ],
        ),
    ]
