# Generated by Django 3.0.5 on 2020-04-14 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grader', '0002_t_pengguna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_pengguna',
            name='id_pengguna',
        ),
        migrations.AlterField(
            model_name='t_pengguna',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
