# Generated by Django 3.0.5 on 2020-04-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0003_auto_20200414_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_pengguna',
            name='username',
            field=models.CharField(max_length=15),
        ),
    ]
