# Generated by Django 3.0.5 on 2020-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_auto_20200414_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_pengguna',
            name='kelas',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
