# Generated by Django 3.0.5 on 2020-04-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_t_pengguna_kelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_pengguna',
            name='username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
