# Generated by Django 3.0.5 on 2020-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_auto_20200416_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_matkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mapel', models.CharField(max_length=15)),
                ('username_dosen', models.CharField(max_length=15)),
            ],
        ),
    ]
