# Generated by Django 3.0.5 on 2020-04-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0010_t_matkul'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_matkul',
            name='kelas',
            field=models.CharField(choices=[('SI 43 01', 'SI 43 01'), ('SI 43 02', 'SI 43 02'), ('SI 43 03', 'SI 43 03')], default='SI 43 01', max_length=15),
        ),
    ]
