# Generated by Django 3.0.5 on 2020-04-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0012_auto_20200416_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(max_length=5)),
                ('index', models.CharField(max_length=5)),
                ('nama', models.CharField(max_length=50)),
                ('kelas', models.CharField(choices=[('SI 43 01', 'SI 43 01'), ('SI 43 02', 'SI 43 02'), ('SI 43 03', 'SI 43 03')], default='SI 43 01', max_length=15)),
                ('nama_mapel', models.CharField(max_length=50)),
            ],
        ),
    ]
