# Generated by Django 3.0.5 on 2020-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0013_t_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_pengguna',
            name='nama_lengkap',
            field=models.CharField(default='nama', max_length=50),
        ),
    ]
