# Generated by Django 3.0.5 on 2020-04-18 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0014_t_pengguna_nama_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_matkul',
            name='nama_dosen',
            field=models.CharField(default='nama', max_length=50),
        ),
    ]
