# Generated by Django 3.0.5 on 2020-04-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0015_t_matkul_nama_dosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_nilai',
            name='index',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=5),
        ),
    ]
