# Generated by Django 3.0.5 on 2020-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0017_auto_20200419_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_matkul',
            name='kode_mapel',
            field=models.CharField(default='kode', max_length=20),
        ),
    ]
