# Generated by Django 3.0.5 on 2020-04-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0019_t_nilai_kode_mapel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_nilai',
            name='kelas',
            field=models.CharField(choices=[('SI4301', 'SI4301'), ('SI4302', 'SI4302'), ('SI4303', 'SI4303')], default='SI 43 01', max_length=15),
        ),
    ]
